default_channel: local
block_shortcuts_when_cancelled: true
send_fake_message_to_chat: true
maintain_spy_mode: false
format:
  default: '{color}[{nick}] {groupprefix}{rank}{vip}{tag}{clantag}&f{sender}{color}: {msg}'
  spy: '&8[SPY] &7{msg}'
private_message_format:
  send: '&6[&ePara {receiver}&6]&f: {msg}'
  receive: '&6[&eDe {sender}&6]&f: {msg}'
  spy: '&8[SPY] &f{ignored} &7[{sender} -> {receiver}] {msg}'